### PR TITLE
dotfiles: alias hub as git only if it's present in system

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nathanchance** [comment]
```
if command -v hub >/dev/null; then
    alias git=hub
fi
```

is a more portable way of doing what this patch does.

**Comment by ghost** [comment]
Thanks dost

**Comment by msfjarvis** [comment]
Well, these are personal scripts and I __always__ install `hub` so I don't see any reason to merge this.

**Comment by ghost** [comment]
Thanks.

**Pull request closed without merging**
